services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file: .env
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - sqldata:/var/opt/mssql
  db-init:
    depends_on:
      - database
    image: mcr.microsoft.com/mssql-tools:latest
    env_file: .env
    command:
      - /bin/sh
      - -c
      - |
        until /opt/mssql-tools/bin/sqlcmd -S database -U sa -P ${MSSQL_SA_PASSWORD} -Q \
          "IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'UmbracoCMS')
          CREATE DATABASE UmbracoCMS"
        do
          echo Retry...
          sleep 1
        done
    restart: "no"
  umbraco:
    depends_on:
      db-init:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    environment:
      ConnectionStrings__umbracoDbDSN: >-
        Server=database;
        User Id=sa;
        Password=${MSSQL_SA_PASSWORD};
        Database=UmbracoCMS;
        TrustServerCertificate=true;
    ports:
      - 8080:8080
    volumes:
      - media:/app/wwwroot/media
volumes:
  media:
  sqldata:
