services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - 5434:1433
    volumes:
      - sqldata:/var/opt/mssql
  db-init:
    depends_on:
      - database
    image: mcr.microsoft.com/mssql-tools:latest
    command:
      - /bin/sh
      - -c
      - |
        until /opt/mssql-tools/bin/sqlcmd -S database -U sa -P Pass@word -Q \
          "IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'UmbracoCMS')
          CREATE DATABASE UmbracoCMS"
        do
          echo Retry...
          sleep 1
        done
    restart: no
  umbraco:
    depends_on:
      db-init:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - media:/app/wwwroot/media
volumes:
  media:
  sqldata:
